// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBsUqRjVnZZX5OsTfFqrJI7g3a9EYBSd0',
    appId: '1:923931445214:web:031e4a8af96972ce66ff4f',
    messagingSenderId: '923931445214',
    projectId: 'fir-803ab',
    authDomain: 'fir-803ab.firebaseapp.com',
    databaseURL: 'https://fir-803ab-default-rtdb.firebaseio.com',
    storageBucket: 'fir-803ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCif58jwH38VlAE_nN8mNo1TV9GnFE6LV4',
    appId: '1:923931445214:android:628d36b1ccbf6fbc66ff4f',
    messagingSenderId: '923931445214',
    projectId: 'fir-803ab',
    databaseURL: 'https://fir-803ab-default-rtdb.firebaseio.com',
    storageBucket: 'fir-803ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiycEFHehACtxaUvpdtg2cba5L7aIVIcY',
    appId: '1:923931445214:ios:262e0d6d2315035066ff4f',
    messagingSenderId: '923931445214',
    projectId: 'fir-803ab',
    databaseURL: 'https://fir-803ab-default-rtdb.firebaseio.com',
    storageBucket: 'fir-803ab.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiycEFHehACtxaUvpdtg2cba5L7aIVIcY',
    appId: '1:923931445214:ios:262e0d6d2315035066ff4f',
    messagingSenderId: '923931445214',
    projectId: 'fir-803ab',
    databaseURL: 'https://fir-803ab-default-rtdb.firebaseio.com',
    storageBucket: 'fir-803ab.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBsUqRjVnZZX5OsTfFqrJI7g3a9EYBSd0',
    appId: '1:923931445214:web:dc4926c5ad156f6766ff4f',
    messagingSenderId: '923931445214',
    projectId: 'fir-803ab',
    authDomain: 'fir-803ab.firebaseapp.com',
    databaseURL: 'https://fir-803ab-default-rtdb.firebaseio.com',
    storageBucket: 'fir-803ab.firebasestorage.app',
  );

}